<div class="phase3_1">
<p>Select the type of data you want to insert for each user:</p>
	<table class="phaseTable">
	<tbody>
		<tr>
			<td class="firstCol">
				<button type="button">Just the username!</button>
				<input type="hidden" name="dataType" value="username" />
			</td>
			<td class="secondCol">
				<h1>What happens in this case?</h1>
				<p>When you specify just the username, you have to communicate manually to each user the password generated by the system.</p>
				<p><em>You have to specify a unique user identifier for each user.</em></p>
			</td>
		</tr>
		<tr>
			<td class="firstCol">
				<button type="button">Just the email!</button>
				<input type="hidden" name="dataType" value="email" />
			</td>
			<td class="secondCol">
				<h1>What happens in this case?</h1>
				<p>If you specify the email address, the password will be sent automatically to the users by the system</p>
				<p><em>Be sure that you have a valid email address for each user.</em></p>
			</td>
		</tr>

	</tbody>
	</table>
</div>
<script type="text/javascript">
(function($) {
	$(document).ready( function() 
	{
		$('div.phase3_1 button').button().click( function( event )
		{
			event.preventDefault();
			var url = "./createNewGame.php";
			var dataType = $(this).next().val();
			var dataToSend = { destinationPhase: 3,
								comingPhase: 3,
								usingAjax: 'true',
								dataType: dataType };
			var typeOfDataToReceive = 'html';
			var callback = function( response ) {
				$("#wrapper").html( response );
			};
			$.post( url, dataToSend, callback, typeOfDataToReceive );
		});
	});
})(jQuery);
</script>